[project]
name = "demo-nats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.13",
    "nats-py[nkeys]>=2.10.0",
    "nkeys>=0.2.1",
    "pynacl>=1.5.0",
    "sqlmodel>=0.0.24",
    "uvicorn>=0.34.3",
]
